### ISSUE TITLE
Parse JSON

### ISSUE THREAD

**Issue by rbeall-quotient** [rbeall-quotient/ogmt-wp#1]
**Description:**

Need to be able to parse JSON string returned from EDAN Object Group such that individual values can be extracted by name and formatted/displayed on screen. 

**Requirements:**

- Successfully Decode JSON result in PHP and store. 
- Withdraw values from JSON depending on key. 
- Add validation and error handling. 

**Tasks:**

- [x] Decode JSON in routes.php and test for errors
- [x] Withdraw and display a test value from decoded JSON
- [x] Add validation code.

**Comment by rbeall-quotient** [comment]
Simple JSON decoding has been added. In the context of the broader project, this is a good stopping point (very basic validation and successful decoding). Will build out as necessary in the next tasks.
